# Secrets Env
# CHISEL_AUTH
# CHISEL_SERVER
# DB_NAME
# DB_PORT
# DB_USER_PASS

name: Backup Database CI

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 7,17 * * *'

jobs:
  backup:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Chisel Tunnel
        env:
          CHISEL_VERSION: "1.11.5"
          CHISEL_AUTH: ${{ secrets.CHISEL_AUTH }}
          CHISEL_SERVER: ${{ secrets.CHISEL_SERVER }}
          DB_PORT: ${{ secrets.DB_PORT }}
        run: |
          echo "Downloading Chisel v${CHISEL_VERSION}..."
          curl -sL https://github.com/jpillora/chisel/releases/download/v${CHISEL_VERSION}/chisel_${CHISEL_VERSION}_linux_amd64.gz | zcat > chisel
          chmod +x chisel

          echo "Establishing tunnel..."
          ./chisel client --auth "$CHISEL_AUTH" "$CHISEL_SERVER" "$DB_PORT:localhost:$DB_PORT" &
          
          # 3. Wait for tunnel initialization
          sleep 5

      - name: Postgres Dump Backup
        uses: tj-actions/pg-dump@v3
        with:
          database_url: "postgres://${{ secrets.DB_USER_PASS }}@localhost:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}"
          postgresql_version: "16"
          path: "backups/now.sql" 
          options: "-O"

      - name: Rename file
        run: |
          mv "./backups/now.sql" "./backups/$(TZ="Asia/Jakarta" date +"%d-%B-%Y_%H:%M:%S.sql")"

      - name: Push new backup to backups folder
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          TIMESTAMP=$(TZ="Asia/Jakarta" date +"%Y-%m-%dT%H:%M:%S%z")

          git add backups; git commit -m "[DB BACKUP] $TIMESTAMP"
          git push
